services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm run dev"
    environment:
      DATABASE_URL: 'postgres://user:pass@db:5432/k_on_line'
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/node_modules
      o: bind
networks:
  snowboard_default:
    external: true
