name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  frontend:
    name: Frontend Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Biome check
        run: npm run check

      - name: TypeScript check
        run: npm run ts

      - name: Run tests
        run: npm run test

      - name: Setup env
        run: cp .env.example .env.local
        
      - name: Build
        run: npm run build
