name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master
      - dev

jobs:
  frontend:
    name: Frontend Checks
    runs-on: ubuntu-latest
    concurrency:
      group: frontend-ci-${{ github.ref }}-${{ matrix.command }}
      cancel-in-progress: true
    strategy:
      matrix:
        command: [check, ts, ci-build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Ran ${{ matrix.command }}
        run: npm run ${{ matrix.command }}
