name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master
      - dev

jobs:
  frontend:
    name: Frontend Checks
    runs-on: ubuntu-latest
    concurrency:
      group: frontend-ci-${{ github.ref }}-${{ matrix.command }}
      cancel-in-progress: true
    strategy:
      matrix:
        command: [check, ts, build]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Set up environment variables
        # ここで最低限のダミー値を設定
        run: |
          echo "NEXT_PUBLIC_APP_URL=https://example.com" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_API_URL=https://api.example.com" >> $GITHUB_ENV
          echo "NODE_ENV=production" >> $GITHUB_ENV
          echo "API_KEY=dummy-ci-key" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_GA_ID=" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_ADS_ID=" >> $GITHUB_ENV
          echo "MAINTENANCE_MODE=" >> $GITHUB_ENV
          echo "MAINTENANCE_WHITELIST=" >> $GITHUB_ENV

      - name: Run ${{ matrix.command }}
        run: npm run ${{ matrix.command }}
